name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run:  cd srcipts && .\build.ps1
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MDrive
        path: 
          .\srcipts\MDrive.zip
